# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-EF4RT8TJS9'

menu:
# - {name: 'About me',   url: 'about.html'}
- {name: 'CV', url: './assets/daegyulim_cv.pdf'}
- {name: 'Publications', url: 'publication.html'}
- {name: 'Projects', url: './menu/project.md'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'News',   url: 'news.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa fa-instagram',  link: 'https://www.instagram.com/robotanddg/'}
- {icon: 'fa fa-youtube',  link: 'https://www.youtube.com/channel/UCl0WmtUmHbrGu8enWfZC94A'}
- {icon: 'fa fa-linkedin',   link: 'https://www.linkedin.com/in/daegyu-lim-b98a9b20b/'}
- {icon: 'fa fa-google',     link: 'https://scholar.google.com/citations?user=CTjBiRYAAAAJ&hl=en'}
- {icon: 'fa fa-github',     link: 'https://www.github.com/DaegyuLim'}
- {icon: 'fa fa-twitter',    link: 'https://twitter.com/DaegyuLim'}
- {icon: 'fa fa-envelope',   link: 'mailto:dgyo3784@snu.ac.kr'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'

# post_date_prefix: 'Written on'
